name: Deploy GradeStar
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SERVER_KEY }}

    - name: Deploy to server
      run: |
        ssh -p 1394 -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_SERVER_IP }} "
          cd ${{ secrets.DEPLOY_SERVER_DIR }} &&
          git remote set-url origin https://kevohmwach:${{ secrets.MY_PAT }}@github.com/kevohmwach/gradestar.git
          git pull origin main &&
          composer install --no-interaction &&
          composer require mews/purifier &&
          php artisan config:clear &&
          php artisan cache:clear &&
          npm install &&
          npm run build
        "
        
